services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=my_pwd
    ports:
      - 3306:3306
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_pwd"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  api:
    image: caroolt/cp-2-microservices-and-web-engineering:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USER=root
      - DB_PASSWORD=root_pwd
    networks:
      - app-networks

networks:
  app-networks: